### ISSUE TITLE
Import error and prepare pickle files from CSV directly.

### ISSUE THREAD

**Issue by ravindra-ut** [basma-b/dual_encoder_udc#1]
Hi,
   There is small import error in dual_encoder.py
``
+from utilities.data_helper import compute_recall_ks, str2bool
``
I have also attached file(as txt but actually python code) which directly generates pkl from csv file with simplified code(IMO).
[prepare_dataset_from_csv.txt](https://github.com/basma-b/dual_encoder_udc/files/1472140/prepare_dataset_from_csv.txt)

**Comment by basma-b** [comment]
Thanks, the import error is fixed now.
Please submit a pull request for the script you provided.
